### ISSUE TITLE
Bringing up to a newer standard than R12

### ISSUE THREAD

**Issue by iceblu3710** [gdsestimating/dxf-parser#13]
Are there currently any plans to bring the parser up to current file standards. Currently all R12 entities are supported it looks like but some program seem to be dropping R12 export/save capabilities.

**Comment by bzuillsmith** [comment]
The parser is far from complete. Only the most common entities are supported. I have been working off the 2014 reference I think. What is it that you need exactly? Any particular entities giving you trouble?

**Comment by iceblu3710** [comment]
The ones that are supported work great.

Splines are probably the biggist thing missing right now. 

Most issues are only on my end. Text reference and rotation is challanging. I have got MTEXT font info and styling working though.

**Comment by octavius37** [comment]
I came here to ask the same question, currently working on a project where the client requires text rotation in Three.js rendered dxfs (so both this and three-dxf are truly great and I cannot thank you enough for them). I don't really know much about the dxf standard, but I added a case for the text rotation code to add a rotation property to the entity, pretty straightforward as far as I can tell. I can submit a pull request if it would help?

**Comment by bzuillsmith** [comment]
@octavius37 absolutely! Pull requests are always welcome as I have not had lots of free time to maintain this lately. But I'm happy to spend a little bit on merging pull requests and publishing fixes

**Comment by iceblu3710** [comment]
Rotation info would be greatly appreciated. A case for the text anchor location (RC,RB,RT,etc) would be fantastic too as text is related LT in a dxf which is kind of wierd.

**Comment by bzuillsmith** [comment]
I added rotation to MText in the latest release because it was rather simple to do. The anchor location will have to come in a later release. I'm going close this thread and if there are specific properties not supported that you want, you can open a new issue for those specifically. Again, I never really got this working to any full spec. I just started with the most common entities and data people use in their dxf drawings and slowly expanding the support from there.
