### ISSUE TITLE
Wrong AutoCadColorIndex

### ISSUE THREAD

**Issue by Serthys** [gdsestimating/dxf-parser#33]
I think some colors on dxf-parser/lib/AutoCadColorIndex.js are wrong or maybe the definition changed.
I've checked some of them, for example, the AutoCadColorIndex[154] = 19608 = 0x004C98 = (0, 76, 152) and on my AutoCAD 2014 the indexed color 154 is (0, 63, 127).
I investigated a bit to find the correct colors and I found some ACI (AutoCAD Color Index) tables but those don't match either.
[ACI table 1](http://sub-atomic.com/~moses/acadcolors.html)[154] = (0, 64, 129)
[ACI table 2](http://help.geosecma.se/17.0/sv/desktop/acadcolors.html)[154] = (0, 76, 153)
I'm not sure how to fix this.

**Comment by bzuillsmith** [comment]
Yeah, I imagine these indexes are actually application specific. I don't remember where I got the table that generated the list in dxf-parser. We have two possible approaches:

1.  Make it extendable so the index table can be changed
2.  Store the color index in the parsed data so that whatever program reads the parsed data can determine the color to display for each index.
