### ISSUE TITLE
output to SVG?

### ISSUE THREAD

**Issue by t3db0t** [gdsestimating/dxf-parser#43]
Has anyone used this to convert to SVG? Or is there already an open-source API for converting DXF (ideally DWG) to SVG?

**Comment by Serthys** [comment]
A bit of googling let me to [this](https://mt236.wordpress.com/2016/03/26/using-three-js-to-render-to-svg). There's even a [demo](https://www.marciot.com/blog-demos/three-to-svg/). Looks like a good starting point.

**Comment by t3db0t** [comment]
Oh, hm. I'm coming from the perspective of a 2D cad floor plan (DWG actually), just looking to convert that straight into an SVG. I've found a smattering of things after a lot of googling, but there doesn't seem to be anything clear-cut.

**Comment by bzuillsmith** [comment]
You'll find very little support for DWG out in the open source world because it's pretty much Adobe's proprietary format. I think they license out the ability for other software to have capabilities to read and write but I'm not entirely sure how all that works.

If you export your DWG to DXF, there is this library developed by @bjnortier https://www.npmjs.com/package/dxf which focuses on parsing dxf into SVG.

**Comment by bjnortier** [comment]
Caveat - my library does convert DXF to SVG, but it doesn't support SVG elements like <circle> etc., all entities are rendered as polylines. 

This is because it was initially developed to render DXFs to Three.js, so everything is converted to polylines.
